name: FortuneWheel
version: '1.21.1-SNAPSHOT'
main: fortunewheel.fortunewheel.FortuneWheel
api-version: 1.19
authors: [ Wood ]
description: Wood's Fortune Wheel
website: https://discord.gg/hfUCBPTq4j
commands:
  lottery:
      description: Spin the wheel!
      usage: /lottery
      aliases: l
      permission: lottery
  buyvoucher:
      description: buy vouchers!
      usage: /buyvoucher
      aliases: bv
      permission: buyvoucher
  reloadconfig:
    description: Reloads the config
    usage: /reloadconfig
    aliases: rcfg
    permission: reloadconfig
  prizes:
    description: shows the current prizes
    usage: /prizes
    aliases: prz
    permission: prizes
  sendgold:
    description: send gold to other players
    usage: /sendgold
    aliases: sg
    permission: sendgold
  setlotteryprize:
    description: set the lottery prize
    usage: /setlotteryprize
    aliases: slp
    permission: setlotteryprize
  playdice:
    description: play a game of dice with another player
    usage: /playdice
    aliases: pd
    permission: playdice

